from setuptools import setup

setup(
    name="wolof_translate",
    version="0.0.1",
    author="Oumar Kane",
    author_email="oumar.kane@univ-thies.sn",
    description="Contain function and classes to process corpora for making translation between wolof text and other languages.",
    install_requires=[
        "accelerate==0.33.0",
        "torch==2.5.1",
        "spacy==3.8.4",
        "nltk==3.7",
        "gensim==4.3.3",
        "furo==2023.5.20",
        "streamlit==1.40.0",
        "tokenizers==0.21.1",
        "tensorboard==2.18.0",
        "evaluate==0.4.0",
        "transformers==4.50.3",
        "pandas==2.2.1",
        "numpy==1.26.4",
        "scikit-learn==1.1.0",
        "matplotlib==3.10.1",
        "plotly==5.14.1",
        "sacrebleu==2.4.2",
        "nlpaug==1.1.11",
        "wandb==0.18.6",
        "pytorch-lightning==2.3.0",
        "selenium==4.10.0",
        "sentencepiece==0.2.0",
        "peft==0.12.0",
        "rouge-score==0.1.2",
        "sacrebleu==2.4.2"
    ],
)
